### PR TITLE
Revert all experimental cross module opt related code

### PR DESCRIPTION
**Pull request by kateinoigakukun**
Unfortunately, my CMO related code makes it hard to maintain our fork, so I decided to revert it 😢

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
Do we still need `swiftStandaloneRuntime` here? It's currently causing build errors:

```
WebAssemblyToolChains.cpp:166:36: error: no member named 'OPT_no_stdlib_link' in namespace 'swift::options'; did you mean 'OPT_no_stdlib_rpath'?
14275
  if (context.Args.hasArg(options::OPT_no_stdlib_link)) {
14276
                          ~~~~~~~~~^~~~~~~~~~~~~~~~~~
14277
                                   OPT_no_stdlib_rpath
```

**Comment by kateinoigakukun** [comment]
Ah, no. it's not necessary anymore.

**Comment by kateinoigakukun** [comment]
After CI succeed, I want to merge this PR by squash-merge to be easily restored again

**Review by MaxDesiatov — APPROVED** [review]
Thanks!

**Comment by MaxDesiatov** [comment]
I assume we need to cherry-pick this to 5.5 as well?

**Comment by kateinoigakukun** [comment]
Fortunately, 5.5 doesn't include new-driver thing and doesn't have big conflict, so I think we don't need to cherry-pick this.

**Pull request merged**
