### PR TITLE
Enable distributed actors in development snapshots

### PR DESCRIPTION
**Pull request by MaxDesiatov**
This would potentially allow us to implement a distributed actors runtime with WebAssembly clients communicating via RPC with other clients or servers written in Swift.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@kateinoigakukun I'm not sure this error is sporadic, I'm seeing it here again after restarting the macOS build, and lates builds from `swiftwasm` branch have the same failures

**Comment by kateinoigakukun** [comment]
Can we utilize distributed actor by having transport implementation on browser?

**Review by kateinoigakukun — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
Yes, that's my current understanding. In the real world scenario servers would need to support "singleton" actors for things like database access, otherwise spawning a separate database actor on the server for every client would be prohibitive from the performance perspective. But from what I gathered, this [already works in the cluster sample code](https://github.com/apple/swift-distributed-actors/blob/eb1201cbf6e93e76293ec2419ae33166dfc510af/Sources/ActorSingletonPlugin/ActorSingletonManager.swift) apparently.

**Comment by MaxDesiatov** [comment]
Also, that Apple's sample repository has multiple branches, only one of them utilizes new `DistributedActorSystem` protocol  [from the proposal](https://github.com/apple/swift-evolution/blob/main/proposals/0344-distributed-actor-runtime.md) that we'd have to implement for things to work on our side.

**Pull request merged**
