### PR TITLE
Fix broken test script

### PR DESCRIPTION
**Pull request by kateinoigakukun**

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
```
2020-09-27T07:47:42.3307995Z error: failed to run `/home/runner/work/swift/target-build/Ninja-ReleaseAssert/swift-linux-x86_64/test-wasi-wasm32/stdlib/Output/Runtime.swift.gyb.tmp.out`
2020-09-27T07:47:42.3309182Z │   1: WASI execution failed
2020-09-27T07:47:42.3309748Z │   2: failed to run WASI `_start` function
2020-09-27T07:47:42.3310363Z │   3: RuntimeError: call stack exhausted
2020-09-27T07:47:42.3311020Z            at $s1ayycfU0_ (Runtime.swift.gyb.tmp.out[35]:0xffffffff)
2020-09-27T07:47:42.3312218Z            at $s14StdlibUnittest9TestSuiteC04_runC04name9parameterySS_SiSgtF (Runtime.swift.gyb.tmp.out[22458]:0x44a5c3)
2020-09-27T07:47:42.3314847Z            at $s14StdlibUnittest14_ParentProcessC10runOneTest04fullG4Name9testSuite0J00J9ParameterAC01_G6StatusOSS_AA0gK0CAL01_G0VSiSgtF (Runtime.swift.gyb.tmp.out[22484]:0x452c6a)
2020-09-27T07:47:42.3317277Z            at $s14StdlibUnittest14_ParentProcessC3runyyF (Runtime.swift.gyb.tmp.out[22494]:0x456f63)
2020-09-27T07:47:42.3318724Z            at $s14StdlibUnittest11runAllTestsyyF (Runtime.swift.gyb.tmp.out[22502]:0x45b45d)
2020-09-27T07:47:42.3319725Z            at main (Runtime.swift.gyb.tmp.out[32]:0x14c94)
2020-09-27T07:47:42.3320417Z            at main (Runtime.swift.gyb.tmp.out[30656]:0x76d2b9)
2020-09-27T07:47:42.3321121Z            at __main_void (Runtime.swift.gyb.tmp.out[30657]:0x76d335)
2020-09-27T07:47:42.3321870Z            at __original_main (Runtime.swift.gyb.tmp.out[30654]:0x76d27a)
2020-09-27T07:47:42.3322606Z            at _start (Runtime.swift.gyb.tmp.out[30]:0x111ad)
2020-09-27T07:47:42.3323237Z ╰─> 4: stk_ovf
2020-09-27T07:47:42.3323421Z 
2020-09-27T07:47:42.3323750Z --
```

Is this caused by that wasmer bug?

**Review by MaxDesiatov — APPROVED** [review]

**Comment by kateinoigakukun** [comment]
Yes, I think. (I have not reported the bug yet.)

**Comment by kateinoigakukun** [comment]
Hmm, JUnit result file is still empty. 🤔

**Comment by kateinoigakukun** [comment]
I checked `lit-tests.xml` is there.

**Comment by MaxDesiatov** [comment]
There's something wrong with the `macos-test-results` archive, I can't unpack it:

```
% unzip macos-test-results.zip 
Archive:  macos-test-results.zip
  inflating: swift-test-results.tar.gz  
maxd@Maxs-MacBook-Pro:~/Downloads% tar xzvf swift-test-results.tar.gz 
x ../target-build/Ninja-ReleaseAssert/swift-macosx-x86_64/swift-test-results/: Path contains '..'
x ../target-build/Ninja-ReleaseAssert/swift-macosx-x86_64/swift-test-results/wasm32-unknown-wasi/: Path contains '..'
x ../target-build/Ninja-ReleaseAssert/swift-macosx-x86_64/swift-test-results/wasm32-unknown-wasi/clang-module-cache/: Path contains '..'
x ../target-build/Ninja-ReleaseAssert/swift-macosx-x86_64/swift-test-results/wasm32-unknown-wasi/completion-cache/: Path contains '..'
x ../target-build/Ninja-ReleaseAssert/swift-macosx-x86_64/swift-test-results/wasm32-unknown-wasi/lit-tests.xml: Path contains '..'
x ../target-build/Ninja-ReleaseAssert/swift-macosx-x86_64/swift-test-results/wasm32-unknown-wasi/completion-cache/FooSwiftModuleOverlay-S7KU4HNLN4JP.completions: Path contains '..'
```

And there are many more lines like that for `completion-cache` files probably shouldn't be archived and uploaded in the first place?

**Comment by kateinoigakukun** [comment]
`completion-cache` is useful when reproducing the test failure

**Review by MaxDesiatov — APPROVED** [review]
This is awesome, thank you 🙏

**Pull request merged**
