### PR TITLE
[WASM] Update WASI SDK to 0.2.0

### PR DESCRIPTION
**Pull request by kateinoigakukun**
When using wasm-ld in wasi-sdk 0.1.0-swiftwasm, some test cases in swift are failed with "failed to demangle witness for associated type 'Iterator' in conformance 'Swift.UInt64.Words: Sequence' from mangled name '$e'" message.

This message means that runtime library fails to look up for protocol conformance from swift5_protocol_conformances section. In WebAssembly binary, these protocol conformances data are stored in data segments in each object files and link them into one segment by wasm-ld.

Swift runtime library uses special __start and __stop symbols to point where the metadata section is located. These special symbols are emitted by linker wasm-ld. But wasm-ld in wasi-sdk 0.1.0 emitited them for each data segments without combining them by their name. This causes the
crash if an user code has a protocol conformance because __start and __stop symbols point only the user defined protocol conformance segment.

The wasm-ld bug has been fixed by this patch https://reviews.llvm.org/D64148

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
Wasn't the target branch meant to be `swiftwasm`?

**Comment by karwa** [comment]
I wonder if it might be better to just build LLD along with LLVM and use that instead (or at least offer it as an option)

**Comment by kateinoigakukun** [comment]
@karwa Exactly 👍 Do you think `clang` and `libclang_rt.builtins-wasm32.a` should be also built with Swift LLVM?

**Comment by MaxDesiatov** [comment]
CI is again not triggered for some reason, force merging this, will sort out issues in separate PRs if any appear

**Pull request merged**
