### PR TITLE
Rebase 2020/01/25

### PR DESCRIPTION
**Pull request by kateinoigakukun**
Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
Not sure why CI wasn't triggered here 🤔

**Comment by kateinoigakukun** [comment]
Hmm, I can't figure out the reason too 🤔

**Comment by kateinoigakukun** [comment]
BTW I'm thinking to change the strategy to track upstream changes because rebasing branch is very hard and likely causes big conflict.
I know `merge` commit makes the commit history redundant, but rebasing operation takes more cost. So I'm trying to use [`pull`](https://github.com/wei/pull) Github App which creates merge pull request when upstream branch updated like [this](https://github.com/kateinoigakukun/swiftwasm/pull/23).

This strategy makes conflict as small as possible and more safely because we don't have to use force-push to `swiftwasm` branch.

What do you think about this?

**Comment by MaxDesiatov** [comment]
@kateinoigakukun this makes sense, fine by me 🙂

**Comment by MaxDesiatov** [comment]
This seems to be a GitHub bug, looks like a CI run has started after all when I recreated the PR as MaxDesiatov/swift#1

**Comment by MaxDesiatov** [comment]
Why GitHub Actions does not run for PRs made from this branch is still a mystery to me 🤨

**Comment by karwa** [comment]
One thing that might be worthwhile is to squash many of the earlier changes. There used to be lots of hacks that have since been removed, etc. In fact, the total diff required to get this port working isn't very big at all.

**Comment by MaxDesiatov** [comment]
I agree, I'm also trying to upstream as much of it as possible in small PRs in the next few weeks, which should make the total diff even smaller.

**Comment by kateinoigakukun** [comment]
Now, I'm tracking `apple/master` branch here https://github.com/kateinoigakukun/swiftwasm/tree/swiftwasm

I'll clone this pr and could you force-push [this](https://github.com/kateinoigakukun/swiftwasm/tree/swiftwasm)? I hope this is final force-push.

**Comment by MaxDesiatov** [comment]
cool, that's done now ✅

**Comment by kateinoigakukun** [comment]
@MaxDesiatov Thanks!

**Pull request closed without merging**
