### PR TITLE
Upstream merge 5.3

### PR DESCRIPTION
**Pull request by kateinoigakukun**

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
Is this much different from #1713? 🤔

**Comment by kateinoigakukun** [comment]
This pr attempt to fix build failure without any revert.

**Comment by MaxDesiatov** [comment]
Cool, bear in mind I also applied a revert on our fork of Foundation to always use `swift` path instead of `swift_static`. I wasn't able to make it work with the latter, because CoreFoundation headers are always loaded from `swift` for some reason. Same for `.swiftmodule` files for other modules.

**Comment by kateinoigakukun** [comment]
CI passed 🎉

**Review by MaxDesiatov — APPROVED** [review]

**Pull request merged**
