### PR TITLE
Set SWIFT_COMPILER_VERSION=5.3.0 in build presets

### PR DESCRIPTION
**Pull request by MaxDesiatov**
I'm not sure there's anything else we can and want to include in this release. Let's bump the version and after this PR is merged use that snapshot for a bit as a release candidate. If all goes well, we'll tag it as a proper `wasm-5.3.0` release. 🙌

### CODE REVIEW

**Comment by kateinoigakukun** [comment]
I think `SWIFT_COMPILER_VERSION` should be applied only when publishing a formal release toolchain, so we should split the presets.

**Comment by MaxDesiatov** [comment]
Sorry, I'm not sure I follow. Could you elaborate please?

**Comment by kateinoigakukun** [comment]
Ah, sorry. You mean no more commits will be added in this branch after this PR? If so, please forget my comment.

**Comment by MaxDesiatov** [comment]
Some will be added to track upstream 5.3.1, 5.3.2 etc. But those subsequent commits will be built as snapshots until we bump the version in this branch again to match upstream and tag a new 5.3.x release.

**Review by kateinoigakukun — APPROVED** [review]

**Pull request merged**
