### PR TITLE
Build host toolchain w/o copying it from snapshots

### PR DESCRIPTION
**Pull request by MaxDesiatov**
Currently the host toolchain is copied over to the target WASI toolchain from snapshots downloaded from [swift.org](https://swift.org/download/#snapshots). This is not ideal as snapshots on swift.org are not always fresh and don't always match what we have in the `swiftwasm` branch or even in the upstream `master` branch. This causes issues similar to what can be seen in #1000, where the host toolchain and SDK don't match the target toolchain with this error:

```
error: compiled module was created by an older version of the compiler; 
rebuild 'Swift' and try again: 
/usr/lib/swift/macosx/Swift.swiftmodule/x86_64-apple-macos.swiftmodule
```

The solution is to:
1) build the host toolchain together with the host SDK and SwiftPM as the first part of the CI process
2) install the host products into the `$SOURCE_PATH/host-toolchain-sdk` directory
3) clean up the build directory
4) build the target SwiftWasm SDK
5) install the target SwiftWasm SDK into the `$SOURCE_PATH/install` directory
6) copy over WASI SDK clang/llvm-ar/wasm-ld into the `$SOURCE_PATH/host-toolchain-sdk` directory
6) copy over the target SwiftWasm SDK into the `$SOURCE_PATH/host-toolchain-sdk` directory
7) create an archive from the `$SOURCE_PATH/host-toolchain-sdk` directory

Thus `build-swiftpm.sh` script is no longer needed as SwiftPM is already compiled as a part of the host toolchain, which also avoids similar issues where SwiftPM from upstream snapshots can also be out of sync from what we build here on CI.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@kateinoigakukun I've verified that both Linux and macOS distributions produce valid and working binaries with SwiftPM, the PR is now ready for review 🙂

**Comment by kateinoigakukun** [comment]
@MaxDesiatov Looks good! Building host toolchain from same source is cleaner than before.
My only concern is CI time, Doesn't this new building toolchain job reach the limit of CI time when there is no cache?

**Comment by MaxDesiatov** [comment]
@kateinoigakukun No, it didn't reach the limit even once during my testing. Only the `swift` build directory is cleaned up after the host toolchain is built, and only because `build-script` doesn't reconfigure CMake files properly. Thus, only the SDK (stdlib, runtime etc) is rebuilt, and the toolchain is picked up from the local `build-cache`. I'll bump the cache version after this is merged, which should get the build time closer to 1-2 hours.

**Comment by MaxDesiatov** [comment]
Ok, I see that you're asking "when there is no cache", even in that case I don't think the built time would drastically increase. For the same reason, the only additional time spent here is on building the target SDK, the rest is cached locally during the same build.

**Pull request merged**
