### PR TITLE
Add workflow_dispatch for manual distribution

### PR DESCRIPTION
**Pull request by kateinoigakukun**
This enables us to release it at any time you would like to do.

### CODE REVIEW

**Review by MaxDesiatov — APPROVED** [review]
Wonderful 👏

**Comment by kateinoigakukun** [comment]
@MaxDesiatov BTW, did you disabled nightly distribution job?
Screen Shot 2020-10-30 at 17 05 20

**Comment by MaxDesiatov** [comment]
I don't remember disabling it, I didn't eve know it's possible... 🤔

**Comment by kateinoigakukun** [comment]
OK, I enabled it again.

**Pull request merged**
