### PR TITLE
Merge master with resolved conflicts

### PR DESCRIPTION
**Pull request by MaxDesiatov**
Attempt to resolve conflicts and make CI pass based on #139

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
There seems to be a build breakage somewhere in the new commits with an assertion failure:

```
0  swift                    0x00000001040023d5 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 37
1  swift                    0x0000000104001388 llvm::sys::RunSignalHandlers() + 248
2  swift                    0x00000001040029cc SignalHandler(int) + 268
3  libsystem_platform.dylib 0x00007fff66f9e42d _sigtramp + 29
4  libsystem_malloc.dylib   0x00007fff66f5de71 tiny_malloc_from_free_list + 561
5  libsystem_c.dylib        0x00007fff66e6ea1c abort + 120
6  libsystem_c.dylib        0x00007fff66e6dcd6 err + 0
7  swift                    0x00000001044ca241 swift::SourceManager::closeVirtualFile(swift::SourceLoc) (.cold.5) + 33
8  swift                    0x000000010137159e swift::SourceManager::closeVirtualFile(swift::SourceLoc) + 1038
9  swift                    0x0000000100ff45c6 swift::importer::ClangSourceBufferImporter::resolveSourceLocation(clang::SourceManager const&, clang::SourceLocation) + 822
10 swift                    0x0000000100fd7466 void llvm::function_ref<void (clang::FullSourceLoc, clang::DiagnosticsEngine::Level, llvm::StringRef)>::callback_fn<swift::ClangDiagnosticConsumer::HandleDiagnostic(clang::DiagnosticsEngine::Level, clang::Diagnostic const&)::$_0>(long, clang::FullSourceLoc, clang::DiagnosticsEngine::Level, llvm::StringRef) + 118
11 swift                    0x0000000102879eb6 clang::DiagnosticRenderer::emitDiagnostic(clang::FullSourceLoc, clang::DiagnosticsEngine::Level, llvm::StringRef, llvm::ArrayRef<clang::CharSourceRange>, llvm::ArrayRef<clang::FixItHint>, llvm::PointerUnion<clang::Diagnostic const*, clang::StoredDiagnostic const*>) + 1926
12 swift                    0x0000000100fd6abe swift::ClangDiagnosticConsumer::HandleDiagnostic(clang::DiagnosticsEngine::Level, clang::Diagnostic const&) + 702
13 swift                    0x0000000103c9377e clang::DiagnosticIDs::ProcessDiag(clang::DiagnosticsEngine&) const + 462
14 swift                    0x0000000103c8e0e0 clang::DiagnosticsEngine::EmitCurrentDiagnostic(bool) + 96
15 swift                    0x0000000103c1bbca clang::ModuleMapParser::parseModuleDecl() + 5642
16 swift                    0x0000000103c1b873 clang::ModuleMapParser::parseModuleDecl() + 4787
17 swift                    0x0000000103c223df clang::ModuleMapParser::parseModuleMapFile() + 303
```

happening on this build step:

```
[886/996][ 88%][1130.175s] cd /Users/runner/runners/2.164.0/work/swift/build/Ninja-ReleaseAssert+stdlib-DebugAssert/swift-macosx-x86_64/stdlib/public/core && /usr/local/bin/python /Users/runner/runners/2.164.0/work/swift/swift/utils/line-directive @/Users/runner/runners/2.164.0/work/swift/build/Ninja-ReleaseAssert+stdlib-DebugAssert/swift-macosx-x86_64/stdlib/public/core/iykMQ.txt -- /Users/runner/runners/2.164.0/work/swift/build/Ninja-ReleaseAssert+stdlib-DebugAssert/swift-macosx-x86_64/./bin/swiftc -c -sdk /Users/runner/runners/2.164.0/work/swift/wasi-sdk/share/wasi-sysroot -target wasm32-unknown-wasi -Xcc -D_WASI_EMULATED_MMAN -resource-dir /Users/runner/runners/2.164.0/work/swift/build/Ninja-ReleaseAssert+stdlib-DebugAssert/swift-macosx-x86_64/./lib/swift -Onone -g -D INTERNAL_CHECKS_ENABLED -D SWIFT_ENABLE_RUNTIME_FUNCTION_COUNTERS -D SWIFT_ENABLE_EXPERIMENTAL_DIFFERENTIABLE_PROGRAMMING -module-cache-path /Users/runner/runners/2.164.0/work/swift/build/Ninja-ReleaseAssert+stdlib-DebugAssert/swift-macosx-x86_64/./module-cache -no-link-objc-runtime -enable-library-evolution -Xfrontend -enable-ownership-stripping-after-serialization -Xfrontend -enforce-exclusivity=unchecked -nostdimport -parse-stdlib -module-name Swift -Xfrontend -group-info-path -Xfrontend /Users/runner/runners/2.164.0/work/swift/swift/stdlib/public/core/GroupInfo.json -swift-version 5 -runtime-compatibility-version none -disable-autolinking-runtime-compatibility-dynamic-replacements -warn-swift3-objc-inference-complete -Xfrontend -verify-syntax-tree -Xllvm -sil-inline-generics -Xllvm -sil-partial-specialization -Xcc -DswiftCore_EXPORTS -warn-implicit-overrides -module-link-name swiftCore -force-single-frontend-invocation -parse-as-library -I /Users/runner/runners/2.164.0/work/swift/build/Ninja-ReleaseAssert+stdlib-DebugAssert/swift-macosx-x86_64/./lib/swift/wasi/wasm32 -o /Users/runner/runners/2.164.0/work/swift/build/Ninja-ReleaseAssert+stdlib-DebugAssert/swift-macosx-x86_64/stdlib/public/core/WASI/wasm32/Swift.o @/Users/runner/runners/2.164.0/work/swift/build/Ninja-ReleaseAssert+stdlib-DebugAssert/swift-macosx-x86_64/stdlib/public/core/iykMQ.txt
FAILED: stdlib/public/core/WASI/wasm32/Swift.o 
```

It's a bit hard to bisect because when checking out commits from `master` they don't have our build scripts and other changes, it seems I have to merge those new commits into `swiftwasm` locally and verify that it builds one by one. Getting through it slowly, but any help is appreciated!

**Comment by kateinoigakukun** [comment]
I'll take a look at this issue today 👀

**Comment by kateinoigakukun** [comment]
Last succeeded commit is `75713b8` and first failure commit is `17a3236`.
And the crash log seems to be related with ClangImporter or clang, but the commits between them doesn't have any change related with that.

So I think there should be some changes on swiftwasm/llvm-project. It seems that you rebased that repository yesterday 👀 

I salvaged the commit hash which is before rebased and here is the diff between last succeeded llvm-project and current `swiftwasm/llvm-project`'s `swiftwasm` branch.

https://github.com/apple/llvm-project/compare/090f2eeaf62e47df3ea18c05827829b52c5dbcf3...swift/master

**Comment by kateinoigakukun** [comment]
I found the main reason, I'll push a patch to this branch a little later

**Pull request merged**
