### PR TITLE
Run packaging scripts and smoke test on CI

### PR DESCRIPTION
**Pull request by MaxDesiatov**
Any changes in this repository should be tested with the packaging script and a basic smoke test that compiles `hello.swift` on CI.

In the future packaging and linking scripts should be moved to this repository, `swiftwasm-sdk` and `swiftwasm-package-sdk` projects probably would be archived when that happens. For now we're pulling the scripts from `swiftwasm-package-sdk` as it is.

### CODE REVIEW

**Comment by kateinoigakukun** [comment]
In my local environment, `print` doesn't work yet 😅

**Comment by MaxDesiatov** [comment]
Same for me, not sure if we've stumbled upon the same issue though. I was able to finally link without errors on a Linux box (still getting ar/ranlib errors despite `CMAKE_AR` and `CMAKE_RANLIB` being correctly set), but the output file doesn't produce any output in polyfills and traps in wasmtime. I want to make these errors reproducible on CI, hope this PR will help with that.

**Comment by kateinoigakukun** [comment]
Build fails because of this macro. We need to add Wasm condition here. https://github.com/apple/swift/blob/9884e5019353d1d6a3438b2678baf6a49b61e3af/stdlib/private/StdlibUnittest/SymbolLookup.swift#L15

**Comment by MaxDesiatov** [comment]
Not sure now if that file should be compiled at all, would any `RTLD_DEFAULT` value or `pointerToSwiftCoreSymbol` call be valid for wasm? Most probably it previously wasn't compiled, but started now by mistake after the last rebase.

**Comment by MaxDesiatov** [comment]
This file didn't exist before Oct 24, 2019, that seems to be the explanation 🙂

**Pull request merged**
