### PR TITLE
Support Amazon Linux 2 for SwiftWasm distribution

### PR DESCRIPTION
**Pull request by kateinoigakukun**
We can build the toolchain with below Dockerfile

```dockerfile
FROM amazonlinux:2

WORKDIR /home/ec2-user

# The build needs a package from the EPEL repo so that needs to be enabled.
# https://www.tecmint.com/install-epel-repository-on-centos/
RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

# Update and install needed build packages
RUN yum -y update
RUN yum -y group install "development tools"
RUN yum -y install \
      git cmake clang python swig uuid-devel libicu-devel libedit-devel \
      libxml2-devel sqlite-devel ncurses-devel pkgconfig python-devel \
      python-pkgconfig libbsd-devel libuuid-devel pexpect curl-devel \
      tzdata rsync wget which python-six ninja-build
RUN ln -s /usr/bin/ninja-build /usr/bin/ninja

# Grab an updated version of cmake
RUN wget https://cmake.org/files/v3.16/cmake-3.16.5-Linux-x86_64.tar.gz \
      && tar xvzf cmake-3.16.5-Linux-x86_64.tar.gz \
      && rm cmake-3.16.5-Linux-x86_64.tar.gz

# Add updated version of cmake to path 
ENV PATH="/home/ec2-user/cmake-3.16.5-Linux-x86_64/bin/:${PATH}"


# Bootstrap the swift source and do a full checkout
RUN git clone https://github.com/swiftwasm/swift.git
WORKDIR /home/ec2-user/swift
RUN ./utils/update-checkout --clone --scheme wasm
RUN mkdir /opt/sccache && cd /opt/sccache && \
    wget -O - "https://github.com/mozilla/sccache/releases/download/0.2.13/sccache-0.2.13-x86_64-unknown-linux-musl.tar.gz" | \
      tar xz --strip-components 1 && \
    ln -sf /opt/sccache/sccache /usr/local/bin
RUN ./utils/webassembly/install-wasi-sdk.sh linux ubuntu-18.04

RUN ./utils/webassembly/build-toolchain.sh

```

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
Does this fully resolve https://github.com/swiftwasm/swift/issues/2318?

**Comment by kateinoigakukun** [comment]
Yes 👍

**Comment by MaxDesiatov** [comment]
Do you think that we'll be able to build it within a Docker image on GitHub Actions, or do we need a real Amazon EC2 VM to get CI set up for this?

**Comment by kateinoigakukun** [comment]
Building... https://github.com/swiftwasm/swift/actions/runs/537548641

**Comment by kateinoigakukun** [comment]
Hmm, it seems impossible to build toolchain for amazonlinux2 on docker on GitHub Actions due to the time limit 😢

**Comment by kateinoigakukun** [comment]
@MaxDesiatov  It's ready to merge.
I set up https://github.com/swiftwasm/swiftwasm-buildbot which is an internal repository for build toolchain on my self-hosted runner. And this repository's nightly ci will trigger the buildbot workflow automatically.

**Review by MaxDesiatov — APPROVED** [review]
Seems legit 👍

Is there an easy way to observe logs, test results, and download distributions for a given CI run on the buildbot?

**Comment by kateinoigakukun** [comment]
@MaxDesiatov You can see logs in https://github.com/swiftwasm/swiftwasm-buildbot/actions

**Pull request merged**
