### PR TITLE
Merge SwiftWasm build scripts, thin CMO to 5.4 release

### PR DESCRIPTION
**Pull request by yonihemi**

### CODE REVIEW

**Comment by kateinoigakukun** [comment]
@yonihemi This compiler crash of Concurrency module can be resolved by merging the latest upstream 5.4 branch, I think. I faced the same crash on the main stream.

**Comment by yonihemi** [comment]
You mean based on PR #2756 and with concurrency enabled, right?
This would require your https://github.com/swiftwasm/swift/pull/2763/commits/ff78f61d6e969b802309e47e190e969fe08d1e01 first, I guess.

**Comment by kateinoigakukun** [comment]
> You mean based on PR #2756 and with concurrency enabled, right?
Right

**Comment by kateinoigakukun** [comment]
@yonihemi Sorry for my slow response 🙇  I think https://github.com/apple/swift/pull/35220 this patch will solve current build failure.

**Comment by kateinoigakukun** [comment]
You need to pick this also https://github.com/swiftwasm/swift/commit/2b7d31b70c8001d3c7b429ca84c1146c33ef5e50

**Comment by yonihemi** [comment]
Thank you @kateinoigakukun!

**Review by kateinoigakukun — APPROVED** [review]

**Pull request merged**
