### PR TITLE
Merge main 2021-08-28

### PR DESCRIPTION
**Pull request by kateinoigakukun**

### CODE REVIEW

**Comment by kateinoigakukun** [comment]
Okay, the compiler and stdlib parts have been passed. The rest failing part is the foundation.

**Comment by MaxDesiatov** [comment]
Thanks, I'll have a look at Foundation failures

**Comment by MaxDesiatov** [comment]
@kateinoigakukun it now fails in the integration tests step, failing to find XCTest for wasm32. I do see it built successfully, and even copied to the installable:

```
-- Installing: /Users/runner/work/swift/swift/dist-toolchain-sdk/swift-wasm-DEVELOPMENT-SNAPSHOT-2021-08-31-a/usr/lib/swift_static/wasi/libXCTest.a
17526
-- Installing: /Users/runner/work/swift/swift/dist-toolchain-sdk/swift-wasm-DEVELOPMENT-SNAPSHOT-2021-08-31-a/usr/lib/swift_static/wasi/wasm32/XCTest.swiftdoc
17527
-- Installing: /Users/runner/work/swift/swift/dist-toolchain-sdk/swift-wasm-DEVELOPMENT-SNAPSHOT-2021-08-31-a/usr/lib/swift_static/wasi/wasm32/XCTest.swiftmodule
```

**Comment by kateinoigakukun** [comment]
Another foundation issue
```
wasm-ld: error: /tmp/tmp.nTv25wdpkg/swift-wasm-DEVELOPMENT-SNAPSHOT-2021-09-01-a/usr/lib/swift_static/wasi/libFoundation.a(NSKeyedArchiver.swift.obj): undefined symbol: __CFBinaryPlistWriteToStream
```

**Comment by MaxDesiatov** [comment]
Should be fixed in https://github.com/swiftwasm/swift-corelibs-foundation/commit/b5b8062b10ee9049b4d274ccb1e60ca0e277b92a, restarting the CI run...

**Comment by kateinoigakukun** [comment]
Finally 🎉

**Review by MaxDesiatov — APPROVED** [review]

**Pull request merged**
