### PR TITLE
Fix undefined identifier in WASI

### PR DESCRIPTION
**Pull request by yonihemi**

### CODE REVIEW

**Comment by yonihemi** [comment]
@kateinoigakukun to unblock the build.
Not sure though if this should be done in another branch (like an intermediate branch between `release/5.8` and `swiftwasm-release/5.8`)?

**Comment by kateinoigakukun** [comment]
Thanks! I usually create a branch from `swiftwasm-release/5.8` and merge latest `release/5.8` into the branch, then apply some fixes to check that the changes work well on CI

**Comment by yonihemi** [comment]
It's the `STDERR_FILENO` definition that doesn't get through.

Best solution is probably refactoring to inline function in upstream - I see copies of almost similar same lines in many places.

**Comment by yonihemi** [comment]
> It's the `STDERR_FILENO` definition that doesn't get through.
> 
Which I guess is also just adding an include :)

**Pull request closed without merging**
