### PR TITLE
Check if `pip` is installed in macOS `install-dependencies.sh`

### PR DESCRIPTION
**Pull request by MaxDesiatov**
`pip` is not always installed on macOS, and `pip3` should be enough to build. Let's make the use of `pip` conditional.

### CODE REVIEW

**Comment by kateinoigakukun** [comment]
I think this kind of dependency installation script is hard to maintain and it pollutes the user environment. So I'm thinking of migrating the dependency installation to Nix package manager.

**Comment by MaxDesiatov** [comment]
> I think this kind of dependency installation script is hard to maintain and it pollutes the user environment.
How exactly would it pollute the user environment?

> So I'm thinking of migrating the dependency installation to Nix package manager.
I hope that's not hard to maintain. I currently find it difficult to make the toolchain build on my different machines. For example, `pip` does not seem to be required for the build, `pip3` is enough, but this script still fails on some of my environments. I think the script should either make sure that `pip` is installed, or should require it. And I'm proposing the latter here.

> 
> (And in fact, I didn't expect this script to run outside of CI.)
What's the best way to build a toolchain/SDK distribution locally then?

**Comment by MaxDesiatov** [comment]
>Installations such as pip install or wasmer apparently pollute the user environment.
I understand that, but this PR is actually reducing the chance of that. Right now users always have `pip install` running when they run the build script. With this PR `pip install` is not running at all when `pip` is not installed. Compared to the `swiftwasm` branch this looks like an improvement to me.

I totally agree that the current way we manage dependencies and build scripts is not ideal. But when building this project locally, I always have to keep this change in stash to get anything built. It's a hassle not having this check in the script right now. While the way dependencies are managed is bad in the `swiftwasm` branch, I don't think that this PR is making it any worse, but actually makes things easier for local builds.

**Comment by kateinoigakukun** [comment]
Why do you need to run `install-dependencies.sh` locally repeatedly?
I think what you want to need is `./utils/update-checkout --clone --scheme wasm --skip-repository swift`

**Comment by MaxDesiatov** [comment]
I'm invoking `ci.sh` to build locally, which in turn calls `install-dependencies.sh`. I always calling `ci.sh` since it also runs the test suite after a successful build.

**Comment by kateinoigakukun** [comment]
maybe reasonable

**Review by kateinoigakukun — APPROVED** [review]

**Pull request merged**
