### PR TITLE
Use Yams 5.0.1 to fix Ubuntu 18.04 build

### PR DESCRIPTION
**Pull request by MaxDesiatov**
Currently, as can be seen from logs at https://github.com/swiftwasm/swift/runs/6178363121?check_suite_focus=true compilation of Yams 5.0.0 fails with this error:

```
/home/runner/work/swift/swift/yams/Sources/Yams/YamlError.swift  -Xlinker -soname -Xlinker libYams.so  -L /home/runner/work/swift/swift/host-build/Ninja-Release/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/yams/lib  -L /home/runner/work/swift/swift/host-build/Ninja-Release/foundation-linux-x86_64/lib   -L /usr/lib/gcc/x86_64-linux-gnu/7 -Xlinker -rpath -Xlinker /home/runner/work/swift/swift/host-build/Ninja-Release/foundation-linux-x86_64/lib:  lib/libCYaml.a  -ldispatch  /home/runner/work/swift/swift/host-build/Ninja-Release/foundation-linux-x86_64/lib/libFoundation.so  -lswiftDispatch  -lgcc  -lgcc_s  -lc  -lgcc  -lgcc_s && :
/usr/bin/ld.gold: error: lib/libCYaml.a(api.c.o): requires dynamic R_X86_64_PC32 reloc against 'yaml_realloc' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: lib/libCYaml.a(scanner.c.o): requires dynamic R_X86_64_PC32 reloc against 'yaml_parser_fetch_more_tokens' which may overflow at runtime; recompile with -fPIC
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
```

### CODE REVIEW

**Comment by kateinoigakukun** [comment]
Have you investigated what change in Yams triggers the linking failure?

**Comment by MaxDesiatov** [comment]
Not yet, but this is on my list. LMK if you'd like to keep this open and resolve the issues in upstream Yams, or if merging this as a temporary fix is fine too.

**Comment by kateinoigakukun** [comment]
OK, I've investigated and fixed the issue: https://github.com/jpsim/Yams/pull/353
It seems Yams 5.0.0 doesn't include any breaking change except for the base Swift version requirement, so it's ok for now to downgrade it. The issue happens from 5.0.0, so we can use 4.0.6.

**Comment by kateinoigakukun** [comment]
The PR has been merged just now 😮 It would be better to wait for the new release.

**Comment by MaxDesiatov** [comment]
Ubuntu CI passes now, ready for review

**Review by kateinoigakukun — APPROVED** [review]

**Pull request merged**
